name: Build and upload Windows app artifact

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: 'Headlamp ref/branch/tag'
        required: true
        default: 'main'
      signBinaries:
        description: Sign the binaries
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  build-windows:
    permissions:
      id-token: write # For fetching an OpenID Connect (OIDC) token
      contents: read
      actions: write # needed to upload artifacts
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            runner: windows-2022
          - arch: arm64
            runner: windows-11-arm
    runs-on: ${{ matrix.runner }}
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        path: build-helper
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        repository: kubernetes-sigs/headlamp
        ref: ${{ github.event.inputs.buildBranch }}
        path: headlamp
    - name: Setup nodejs
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: |
          headlamp/app/package-lock.json
          headlamp/frontend/package-lock.json
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.26.*'
        cache-dependency-path: |
          headlamp/backend/go.sum
    - name: Dependencies
      uses: crazy-max/ghaction-chocolatey@dfdcf5bba9c0a16358a21c13a06ec5c89024b3ac # v4.1.0
      with:
        args: install make
    - name: Azure login
      if: ${{ inputs.signBinaries }}
      uses: azure/login@a641126d1b8aa4d1fa005f4f92df94a3a4c4c906 # v3.1.0
      with:
        client-id: ${{ secrets.WINDOWS_CLIENT_ID }}
        tenant-id: ${{ secrets.AZ_TENANT_ID }}
        subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
    - name: Fetch certificates
      if: ${{ inputs.signBinaries }}
      shell: pwsh
      run: |
        az keyvault secret download --subscription ${{ secrets.AZ_SUBSCRIPTION_ID }} --vault-name headlamp --name HeadlampAuthCert --file c:\HeadlampAuthCert.pfx --encoding base64
        az keyvault secret download --subscription ${{ secrets.AZ_SUBSCRIPTION_ID }} --vault-name headlamp --name ESRPHeadlampReqCert --file c:\HeadlampReqCert.pfx --encoding base64
    - name: Set up certificates
      if: ${{ inputs.signBinaries }}
      shell: pwsh
      run: |
        Import-PfxCertificate -FilePath c:\HeadlampAuthCert.pfx -CertStoreLocation Cert:\LocalMachine\My -Exportable
        Import-PfxCertificate -FilePath c:\HeadlampReqCert.pfx -CertStoreLocation Cert:\LocalMachine\My -Exportable

    - name: Download and Set up ESRPClient
      if: ${{ inputs.signBinaries }}
      shell: pwsh
      run: |
        nuget.exe sources add -name esrp -source ${{ secrets.ESRP_NUGET_INDEX_URL }} -username headlamp -password ${{ secrets.AZ_DEVOPS_TOKEN }}
        nuget.exe install Microsoft.EsrpClient -Version 1.2.80 -source  ${{ secrets.ESRP_NUGET_INDEX_URL }} | out-null

    - name: Build Frontend
      shell: pwsh
      working-directory: headlamp
      run: |
        cd frontend
        npm ci
        npm run build

    - name: Install App Dependencies and Setup Plugins
      shell: pwsh
      working-directory: headlamp
      run: |
        cd app
        npm ci
        node --experimental-strip-types scripts/setup-plugins.ts

    - name: Build Windows ${{ matrix.arch }} App
      shell: pwsh
      working-directory: headlamp
      run: |
        if ("${{ inputs.signBinaries }}" -eq "true") {
          $env:ESRP_PATH="$(Get-Location)\..\Microsoft.EsrpClient.1.2.80\tools\EsrpClient.exe"
          $env:HEADLAMP_WINDOWS_CLIENT_ID="${{ secrets.WINDOWS_CLIENT_ID }}"
          $env:HEADLAMP_WINDOWS_SIGN_EMAIL="${{ secrets.WINDOWS_SIGN_EMAIL }}"
        } else {
          echo "Not signing binaries"
        }
        cd app
        npm run package -- --win --${{ matrix.arch }}

    - name: Create MSI for ${{ matrix.arch }}
      if: ${{ matrix.arch == 'x64' }}
      shell: pwsh
      working-directory: headlamp
      env:
        MSI_ARCH: ${{ matrix.arch }}
      run: |
        cd app
        node windows/msi/build.js

    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: Win-${{ matrix.arch }}-exes
        path: ./headlamp/app/dist/Headlamp*${{ matrix.arch }}*.*
        if-no-files-found: error
        retention-days: 2
