name: Build and upload Mac app artifact

on:
  workflow_dispatch:
    inputs:
      buildBranch:
        description: 'Headlamp ref/branch/tag'
        required: true
        default: 'main'
      signBinaries:
        description: Notarize app
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  build-mac:
    runs-on: macos-latest
    permissions:
      contents: read
      actions: write # needed to upload artifacts
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        ref: ${{ github.event.inputs.buildBranch }}
    - name: Setup nodejs
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22.x
        cache: 'npm'
        cache-dependency-path: |
          app/package-lock.json
          frontend/package-lock.json
    - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version: '1.26.*'
        cache-dependency-path: |
          backend/go.sum
    - name: Dependencies
      run: brew install make
    - name: Build Backend and Frontend
      run: |
        make
    - name: Add MacOS certs
      run: cd ./app/mac/scripts/ && sh ./setup-certificate.sh
      env:
        APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
        APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
    - name: Build Signed and Notarized App Mac
      if: ${{ inputs.signBinaries }}
      env:
        APPLE_ID: ${{ secrets.APPLEID }}
        APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLEIDPASS }}
        APPLE_TEAM_ID: ${{ secrets.APPLETEAMID }}
      run: |
        make app-mac 2>&1 | tee build.log
        if grep -q "Mac codesign: Failed" build.log; then
          echo "Error: Mac codesign failed"
          exit 1
        fi
    - name: Build Unsigned App Mac
      if: ${{ ! inputs.signBinaries }}
      run: |
        make app-mac
    - name: Upload artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: dmgs
        path: ./app/dist/Headlamp*.dmg
        if-no-files-found: error
        retention-days: 2
  verify-notarization:
    runs-on: macos-latest
    needs: build-mac
    permissions:
      actions: write # for downloading artifacts
      contents: read
    if: ${{ inputs.signBinaries }}
    strategy:
      matrix:
        arch: [x86, arm64]
    steps:
    - name: Download artifact
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: dmgs
        path: ./dmgs
    - name: Verify Notarization
      run: |
        cd ./dmgs

        # Map x86 to x64
        ARCH=${{ matrix.arch }}
        if [ "$ARCH" = "x86" ]; then
          ARCH="x64"
        fi

        echo "Verifying notarization of the app: $(ls ./Headlamp*${ARCH}*.dmg)"
        MOUNT_OUTPUT="$(hdiutil attach ./Headlamp*${ARCH}*.dmg)"
        VOLUME_NAME="$(echo "$MOUNT_OUTPUT" | grep -o '/Volumes/[^\s]*')"

        # Check if the app is notarized
        echo "Checking volume: $VOLUME_NAME"
        spctl -a -v "$VOLUME_NAME/Headlamp.app/Contents/MacOS/Headlamp"

        echo "Checking symlinks..."
        # Check if the app has symlinks
        SYMLINKS=$(find "$VOLUME_NAME" -type l -ls || true)
        NODE_MODULES_AS_SYMLINKS=$(echo "$SYMLINKS" | grep node_modules || true)
        if [ -n "$NODE_MODULES_AS_SYMLINKS" ]; then
          echo "Symlinks found in the DMG:"
          echo "$NODE_MODULES_AS_SYMLINKS"
          exit 1
        else
          echo "No symlinks found in the DMG"
        fi

        echo "Detaching volume"
        hdiutil detach "$VOLUME_NAME" || true
        exit 0
