name: Publish container
on:
  push:
    tags:
    - 'v*'
  workflow_dispatch:
    inputs:
      buildTag:
        description: 'Headlamp tag (with the "v" prefix)'
        required: true
        type: string
      containerTags:
        description: 'Container tags (separated by a comma)'
        type: string

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: headlamp-k8s/headlamp
jobs:
  push_to_registry:
    name: Test building container image
    runs-on: ubuntu-latest
    permissions:
      packages: write # needed for publishing the container image
    steps:
    - name: Check out the repo
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
    - name: Figure out the tag based on event trigger
      env:
        TRIGGER: ${{ github.event_name }}
      run: |
        CONTAINER_TAGS=${{ github.event.inputs.containerTags }}
        if [ "$TRIGGER" == "workflow_dispatch" ]; then
          echo "TRIGGERED_BY_WORKFLOW_DISPATCH with build tag ${{ github.event.inputs.buildTag }}"
          BUILD_TAG=${{ github.event.inputs.buildTag }}
          if [ -z $CONTAINER_TAGS ]; then
            CONTAINER_TAGS=$BUILD_TAG
          fi
        else
          # on push to a tag, use the latest tag starting with v and latest as the build tag
          BUILD_TAG="$(git tag --list --sort=version:refname 'v*' | tail -1)"
          if [ -z $CONTAINER_TAGS ]; then
            CONTAINER_TAGS="$BUILD_TAG,latest"
          fi
        fi

        # Join all tags with the image name
        TAGS=""
        for TAG in $(echo $CONTAINER_TAGS|tr ',' ' ') ; do \
          TAGS=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${TAG},${TAGS}
        done

        # Remove trailing comma
        TAGS=$(echo $TAGS | sed s/,$//g)

        echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
        echo "CONTAINER_TAGS=$TAGS" >> $GITHUB_ENV
    - name: Print finalised tags
      run: |
        echo "BUILD_TAG=${{ env.BUILD_TAG }}"
        echo "CONTAINER_TAGS=${{ env.CONTAINER_TAGS }}"
    - name: checkout to build branch
      run: |
        git fetch --tags --force origin
        git checkout ${{ env.BUILD_TAG }}
        echo "HEADLAMP_SOURCE_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV
    - name: Log in to the Container registry
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_IMAGES }}
    - name: Build and push Docker image
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        context: .
        build-args: |
          HEADLAMP_SOURCE_COMMIT=${{ env.HEADLAMP_SOURCE_COMMIT }}
        push: true
        pull: true
        platforms: linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
        tags: ${{ env.CONTAINER_TAGS }}
        labels: ${{ steps.meta.outputs.labels }}
        provenance: true
        cache-from: type=gha
        cache-to: type=gha,mode=max
